name: "simple-auth-api"

services:
  mongo:
    container_name: mongo-container
    image: mongo:7
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api-container
    build: .
    image: simple-auth-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/app/dist
      - ./package.json:/app/package.json
    ports:
      - 3333:3333
      - 9222:9222
    links:
      - mongo
